# Generated by Django 5.1.3 on 2024-12-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_content', models.TextField()),
                ('predicted_category', models.CharField(max_length=50)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Email Prediction',
                'verbose_name_plural': 'Email Predictions',
                'ordering': ['-prediction_date'],
            },
        ),
    ]
